### ISSUE TITLE
Clean and Preprocess the Dataset 🧹📃

### ISSUE THREAD

**Issue by Nalito** [mlsanigeria/nigeria-crime-trends#2]
## Clean and Preprocess Crime Dataset

Description: Perform data cleaning, including removing duplicates, handling missing values, and converting date formats. Preprocess the data to create features like crime types, regions, and time-based metrics. Labels: Data Cleaning, Data Preprocessing

### What is Needed
Contributors are needed to perform data cleaning, including removing duplicates, handling missing values, and converting date formats. 

### How to Contribute

- Get familiar with the scripts and documentation already provided in the [repository](https://github.com/mlsanigeria/nigeria-crime-trends).
- Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
- Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

### Getting Started
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/nigeria-crime-trends/blob/main/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

**Comment by peachpanic** [comment]
Hello! Im interested in working on this issue and can contribute especially with Data Cleaning. Is there a deadline for this?

**Comment by Odeyiany2** [comment]
> Hello! Im interested in working on this issue and can contribute especially with Data Cleaning. Is there a deadline for this?

Hello @yoenuts, Thank you for your interest! Contribution to the project starts on Tuesday 1st, October to kickoff the hacktoberfest event but you can start contributing now.

Please follow our [contribution guidelines](https://github.com/mlsanigeria/nigeria-crime-trends/blob/main/CONTRIBUTING.md) 
Create a folder using the project name and your github name under this [folder ](https://github.com/mlsanigeria/nigeria-crime-trends/tree/main/experimentation_%7BGitHub_Username%7D)in the repo. It would contain your notebook. 

We also encourage you to register for our kickoff call to get firsthand information on what we expect from your contributions: [MLSA Hacktoberfest]( https://bit.ly/mlsa-hacktoberfest-2024)

We’re looking forward to your participation!🎉

**Comment by faresbouzayen** [comment]
Hi @Nalito! I’m eager to contribute to the cleaning and preprocessing of the crime dataset! 🧹📃

Plan:
Data Cleaning:

Remove Duplicates: Identify and eliminate any duplicate entries.
Handle Missing Values: Determine appropriate strategies for dealing with missing data (e.g., imputation, removal).
Convert Date Formats: Ensure all date fields are in a standardized format for consistency.
Feature Engineering:

Crime Types: Categorize crimes into defined types for easier analysis.
Regions: Create region-based metrics for spatial analysis.
Time-Based Metrics: Generate features that capture temporal trends (e.g., crime rates over time).
Next Steps:
I’ll review the existing scripts and documentation to understand the current setup and ensure my contributions align with the project's structure.
I’ll also make sure to test my code thoroughly before submitting a pull request.
If there are any specific guidelines or additional details you’d like me to follow, please let me know. I’m looking forward to collaborating with everyone! 🎉

**Comment by Sammybams** [comment]
> Hi @Nalito! I’m eager to contribute to the cleaning and preprocessing of the crime dataset! 🧹📃
> 
> Plan: Data Cleaning:
> 
> Remove Duplicates: Identify and eliminate any duplicate entries. Handle Missing Values: Determine appropriate strategies for dealing with missing data (e.g., imputation, removal). Convert Date Formats: Ensure all date fields are in a standardized format for consistency. Feature Engineering:
> 
> Crime Types: Categorize crimes into defined types for easier analysis. Regions: Create region-based metrics for spatial analysis. Time-Based Metrics: Generate features that capture temporal trends (e.g., crime rates over time). Next Steps: I’ll review the existing scripts and documentation to understand the current setup and ensure my contributions align with the project's structure. I’ll also make sure to test my code thoroughly before submitting a pull request. If there are any specific guidelines or additional details you’d like me to follow, please let me know. I’m looking forward to collaborating with everyone! 🎉

Thank you @faresbouzayen. We'd love your contributions and you can go ahead. Make sure to check the [contribution guidelines](https://github.com/mlsanigeria/nigeria-crime-trends/blob/main/CONTRIBUTING.md) to follow the naming convention and style for making your contributions in this project.

**Comment by Odeyiany2** [comment]
Hii @Sammybams and @Nalito I would like to work on this. Thank you.

**Comment by oree-xx** [comment]
Hi @Sammybams and @Nalito  can I also work on this?

**Comment by Sammybams** [comment]
> Hi @Sammybams and @Nalito can I also work on this?

Yes, you can go ahead @oree-xx.

**Comment by Sammybams** [comment]
> Hii @Sammybams and @Nalito I would like to work on this. Thank you.

Yes, @Odeyiany2. Please do.
