### ISSUE TITLE
Model Development and Evaluation 🧠🤖

### ISSUE THREAD

**Issue by Nalito** [mlsanigeria/nigeria-crime-trends#4]
### What is Needed
Contributors are expected to identify suitable machine learning algorithms for predicting crime fatalities, and train machine learning models using the cleaned and preprocessed dataset. Trained models should also be evaluated using suitable ML metrics.

### How to Contribute

- Get familiar with the scripts and documentation already provided in the [repository](https://github.com/mlsanigeria/nigeria-crime-trends).
- Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
- Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

### Getting Started
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/nigeria-crime-trends/blob/main/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

**Comment by ugz-man** [comment]
Can I work on this?

**Comment by Somyyaa** [comment]
I have pulled a request for issue 4. Kindly review it.

**Comment by MariaMahmood18** [comment]
Can we adopt a deep learning based neural network approach for this?

**Comment by Sammybams** [comment]
> Can we adopt a deep learning based neural network approach for this?

That just might be excessive as we have just about 40k data points and would be prone to overfitting. But you can try it out and make your PR.

**Comment by yusufokunlola** [comment]
#26 
Hello, I developed and evaluated several regression models.
Kindly review.
